# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alberto Madrazo
email: albertomadrazo@gmail.com
# description: > Este es el sitio donde se encuentra mi portafolio de animador y 
# desarrollador web, y enlaces a mis proyectos de programación.
baseurl: ""
url: "http://albertomadrazo.com"
github_username:  albertomadrazo

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM